In [1]:
import pandas as pd 
import numpy as np 

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [19]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
X = data.iloc[:,3:-1].values    # ignoring the feature as: RowNumber, CustomerId, Surname 
y = data.iloc[:,-1].values

In [11]:
print(X.shape)
print(y.shape)

(10000, 10)
(10000,)


In [14]:
# Handling the object data type feacture values 
# feature - Gender 
from sklearn.preprocessing import LabelEncoder 

In [16]:
label = LabelEncoder()
X[:,2] = label.fit_transform(X[:,2])

In [17]:
print(X[:,2])

[0 0 0 ... 0 1 0]


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder 

In [25]:
ct = ColumnTransformer([('encoding',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [28]:
# feature standardization 
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 14)
(2000, 14)
(8000,)
(2000,)


In [32]:
print(X_train)

[[1.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 1.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 1.0 ... 1 0 181429.87]
 [1.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [33]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 1.0 ... 1 0 128702.1]
 [1.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [1.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc = StandardScaler()

In [41]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [42]:
print(X_train)

[[ 0.5698444  -0.5698444   0.5698444  ...  0.64259497 -1.03227043
   1.10643166]
 [-1.75486502  1.75486502 -1.75486502 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497 -1.03227043
   1.41231994]
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497  0.9687384
   0.84432121]
 [-1.75486502  1.75486502 -1.75486502 ...  0.64259497 -1.03227043
   0.32472465]]


In [43]:
print(X_test)

[[-1.75486502  1.75486502 -1.75486502 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497 -1.03227043
   0.49587037]
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [ 0.5698444  -0.5698444   0.5698444  ...  0.64259497 -1.03227043
   0.71888467]
 [-1.75486502  1.75486502 -1.75486502 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.75486502  1.75486502 -1.75486502 ...  0.64259497 -1.03227043
   1.61255917]]


In [45]:
import tensorflow as tf 

In [88]:
ann = tf.keras.models.Sequential()  # instance for tf & Input layer 

In [89]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  # adding first hidden layer 

In [90]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  # adding second hidden layer 

In [91]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))  # adding output layer 

In [92]:
# Till here only architecture of the ANN is made 

In [93]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])  # binding all the layers with each other 

In [94]:
ann.fit(X_train,y_train,batch_size=32, epochs = 150)     # batch_size -> no of sample in each minibatch
                                                        # epochs -> number of times the whole trainning set feeded

Epoch 1/150
250/250 [==============================] - 2s 3ms/step - loss: 0.6348 - accuracy: 0.6651
Epoch 2/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4792 - accuracy: 0.8018
Epoch 3/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4428 - accuracy: 0.8104
Epoch 4/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4252 - accuracy: 0.8174
Epoch 5/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4120 - accuracy: 0.8226
Epoch 6/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3988 - accuracy: 0.8291
Epoch 7/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3857 - accuracy: 0.8403
Epoch 8/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3752 - accuracy: 0.8464
Epoch 9/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3690 - accuracy: 0.8490
Epoch 10/150
250/250 [==============================] - 1s 5ms/step - loss: 0.3644 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.3359 - accuracy: 0.8630
Epoch 82/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3361 - accuracy: 0.8616
Epoch 83/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3359 - accuracy: 0.8612
Epoch 84/150
250/250 [==============================] - 1s 5ms/step - loss: 0.3362 - accuracy: 0.8612
Epoch 85/150
250/250 [==============================] - 1s 5ms/step - loss: 0.3359 - accuracy: 0.8624
Epoch 86/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3360 - accuracy: 0.8620
Epoch 87/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3360 - accuracy: 0.8621
Epoch 88/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 0.8626
Epoch 89/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8622
Epoch 90/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 

In [95]:
print(ann.predict(X_test))

63/63 [==============================] - 0s 3ms/step
[[0.19080459]
 [0.29077554]
 [0.15004715]
 ...
 [0.11529376]
 [0.18518461]
 [0.13495155]]


In [97]:
y_pred=ann.predict(X_test)     
y_pred=(y_pred>0.5)           

63/63 [==============================] - 0s 2ms/step


In [98]:
from sklearn.metrics import confusion_matrix, accuracy_score 

In [100]:
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(f"accuracy score = {accuracy_score(y_test,y_pred)}")

[[1521   74]
 [ 197  208]]
accuracy score = 0.8645


In [ ]:
# with no of neurons in hidden layer = 6 -> 86% accuracy
# with no of neurons in hidden layer = 10 -> 85% accuracy
# with increasing no of epochs for neurons 6 still same 